IF
   InParty(Myself)
    !StateCheck(Myself,CD_STATE_NOTVALID)
    See(Player1)
    !StateCheck(Player1,CD_STATE_NOTVALID)
    CombatCounter(0)
    !See([ENEMY])
	OR(2)
		Global("H#ValygarRomanceActive","GLOBAL",1)
		Global("H#ValygarRomanceActive","GLOBAL",2)
   InParty("Sola")
   Global("H#SolaufeinWarning","GLOBAL",1)
   GlobalGT("SolaTalk","GLOBAL",13)
THEN
   RESPONSE #100
   SetGlobal("H#SolaufeinWarning","GLOBAL",2)
   StartDialogNoSet(Player1)
END
